# User Settings | Edit there as per required

title: accent～老和尚
url: "http://laoheshang.github.io"
baseurl: "/accent"

# This will show up at the top of index page
site_heading: >
    老和尚 <span class="faded"> accent</span>

email: your@email.com
author: yourname
# This description will show up in google search results
# (for index page) etc.
description: >
    accent is, as Trump would put it, the best

# This will what will show against &copy; in the footer
copyright: 2020
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see

# 欢迎文，false，关，true，开

intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro

# 欢迎词，logo，Welcome
short_bio: >
    Welcome! This is <span>accent</span>, a mobile friendly theme for Jekyll. The main feature of this
    theme is that you can change the accent color. Refer the
    <a class="underline different-highlight" href="http://ankitsultana.com/accent/documentation.html">
        Documentation
    </a>
    to know how.

#文本链接路径
permalink: /:title.html

# Comments are powered by disqus
comments: false

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Keep this sentence less than 13 words or it won't look good.

about_footer: false

twitter_username: AnkitSultana
github_username: yourname
facebook_id: yourusername
qq: 12345678
weixin: qinghongjiao

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 16
paginate_path: "/page/:num"
tracking_id: UA-69243 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/accent.png" # This will show in facebook thumbnails
twitter_image: "http://ankitsultana.com/images/accent.png?1234" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
